export const USER_ACTION_TYPES = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	CHECK_USER_SESSEION: "CHECK_USER_SESSEION",
	GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
	EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
	SIGN_IN_SUCCES: "SIGN_IN_SUCCES",
	SIGN_IN_FAILER: "SIGN_IN_FAILER",
	SIGN_UP_START: "SIGN_UP_START",
	SIGN_UP_SUCCES: "SIGN_UP_SUCCES",
	SIGN_UP_FAILER: "SIGN_UP_FAILER",
	SIGN_OUT_START: "SIGN_OUT_START",
	SIGN_OUT_FAILER: "SIGN_OUT_FAILER",
	SIGN_OUT_SUCCES: "SIGN_OUT_SUCCES",
};
